trigger:
- main  # Cambiar a 'master' si tu rama principal se llama así

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
# 1. Instalar el SDK de .NET 10 en el agente de Azure
- task: UseDotNet@2
  displayName: 'Instalar .NET 10 SDK'
  inputs:
    packageType: 'sdk'
    version: '10.x'

# 2. Restaurar los paquetes NuGet (dependencias)
- task: DotNetCoreCLI@2
  displayName: 'Restaurar dependencias (dotnet restore)'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

# 3. Compilar el proyecto (El famoso "Build")
- task: DotNetCoreCLI@2
  displayName: 'Compilar proyecto (dotnet build)'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

# 4. Publicar y empaquetar la API lista para producción
- task: DotNetCoreCLI@2
  displayName: 'Publicar aplicación (dotnet publish)'
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

# 5. Guardar el archivo empaquetado como el "Artefacto" final
- task: PublishBuildArtifacts@1
  displayName: 'Subir Artefacto a Azure Pipelines'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'api-clima-drop'
    publishLocation: 'Container'

#6
- task: Bash@3
  displayName: 'Desplegar API vía ZipDeploy API'
  env:
    # Pasamos la contraseña secreta al script de forma segura
    PASSWORD_SECRETA: $(DeployPassword)
  inputs:
    targetType: 'inline'
    script: |
      # 1. Buscamos el nombre exacto del archivo .zip que se generó
      ZIP_FILE=$(find $(Build.ArtifactStagingDirectory) -name "*.zip" | head -n 1)
      echo "Desplegando archivo: $ZIP_FILE"
      
      # 2. Enviamos el archivo directamente al servidor de Azure
      curl -f -v -X POST -u "$(DeployUser):$PASSWORD_SECRETA" --data-binary @"$ZIP_FILE" https://api-hour-converter-etcpg7cwgmb7fhab.scm.eastus-01.azurewebsites.net/api/zipdeploy